repos:
  - repo: https://github.com/sirosen/check-jsonschema
    rev: a20fe80ebdd4aec6791598c9ff559985580f91ea  # frozen: 0.31.1
    hooks:
      - id: check-github-workflows
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b  # frozen: v5.0.0
    hooks:
      - id: detect-private-key
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/brokenpip3/pre-commit-hooks
    rev: dd7b3821637ba3c3a8628ad487fd84edec8006f2  # frozen: 0.0.1
    hooks:
      - id: github-actions-hash
        files: \.(yml|yaml)$
